Task 3 Full Name Method + Testing
Bjosx/rdyDEV_CodeSpaces pull request #2
Opened 2023-03-26 02:51 UTC by Bjosx

## Description

-Created full_name method for student to return title, first_name, middle_name and last_name as a string.
-Created a factory for the student object using Faker to generate random data.
-Created a spec for the student model and also added a test for the full_name method.

## Type of change

Please select the relevant option.

- [ ] Bug fix
- [ x ] New feature
- [ ] Breaking change
- [ ] Other

## Checklist

Please review the following checklist and ensure all tasks are completed before submitting the pull request:

- [ x ] I have performed a self-review of my own code
- [ x ] I have added tests that prove my fix is effective or that my feature works

2023-03-28 03:39 UTC, Bjosx commented
Not sure how this happened but in updating this branch to include the changes from task 2 I appear to have moved the deletion of the old migration file into this pull request.

2023-04-04 00:08 UTC, m0xfff requested changes
Your code looks generally quite good, but I have a few suggestions. I'll help you remove that migration & rebase onto develop during standup.

2023-04-04 00:08 UTC, m0xfff commented on spec/models/student_spec.rb
> +  describe "#full_name" do
The test case for the `#full_name` method looks good. If you decide to add those model validations you can add test coverage by doing:

```suggestion
  let(:student) { build :student_with_data }
  
  it { should validate_presence_of(:first_name) }
  it { should validate_presence_of(:last_name) }
  
  describe "#full_name" do
```

Also, it might be worth adding a test case to cover the scenario when one of the components is missing i.e. when `middle_name` is `nil`. Pretty sure I told you to only test this case last time we spoke, but I was mistaken, the spirit behind me saying that was that you don't want to get into the habit of testing every possible case because it can lead to an overwhelming amount of test cases, making your test suite difficult to maintain and time-consuming to run. 

Instead, focus on testing the most common and critical scenarios, as well as edge cases that could potentially break the functionality. This will provide a good balance between having a comprehensive test suite and maintaining its manageability. In this case, testing the scenario with a missing `middle_name` is a reasonable addition since it's a common real-world situation and directly related to the `full_name` method's behaviour.

2023-04-12 06:56 UTC, m0xfff requested changes

2023-04-12 06:56 UTC, m0xfff commented on spec/factories/student.rb
> +    end
You can add these attributes to the base `:student` factory, and add the rest of the attributes in a "Factory Bot Trait".

2023-04-12 06:56 UTC, m0xfff commented on spec/models/student_spec.rb
> +      expect(student2.full_name).to eq "#{student2.first_name} #{student2.last_name}"
```suggestion
      expect(student2.full_name).to eq "Matthew White" 
```

2023-04-12 06:56 UTC, m0xfff commented on spec/models/student_spec.rb
> +      expect(student2.full_name).to eq "#{student2.first_name} #{student2.last_name}"
And you'll need to update the definition of `:student2` to include the literal first name & last name.

2023-05-03 06:02 UTC, m0xfff approved these changes
LGTM 👍

2023-05-08 01:24 UTC, merged